"""Compose customer replies using the OpenAI API, price list, and tone guide."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List

from openai import OpenAI


def _load_price_list(path: Path) -> str:
    """Load and format the JSON price list."""
    if not path.exists():
        raise FileNotFoundError(f"Price list file not found: {path}")

    with path.open("r", encoding="utf-8") as price_file:
        data: Dict[str, Any] = json.load(price_file)

    services: Iterable[Dict[str, Any]] = data.get("services", [])
    lines: List[str] = ["Available services and pricing:"]
    for service in services:
        name = service.get("name", "Unnamed service")
        description = service.get("description", "")
        price = service.get("price")
        price_text = f"£{price}" if price is not None else "price upon request"
        if description:
            lines.append(f"- {name} ({price_text}): {description}")
        else:
            lines.append(f"- {name} ({price_text})")

    if len(lines) == 1:
        lines.append("- (No services configured)")

    return "\n".join(lines)


def _load_tone_profile(path: Path) -> str:
    """Load the tone guide markdown file."""
    if not path.exists():
        raise FileNotFoundError(f"Tone profile file not found: {path}")
    return path.read_text(encoding="utf-8").strip()


def _build_system_prompt(price_list: str, tone_profile: str) -> str:
    """Build the system prompt combining tone and service info."""
    return (
        "You are PowWash's virtual assistant replying to WhatsApp enquiries about "
        "exterior cleaning quotes.\n"
        "In every response you must:\n"
        "- Follow the tone guide below.\n"
        "- Reference offerings only from the provided service menu.\n"
        "- Gather any missing details that affect pricing (surface type, size, access, preferred times).\n"
        "- Offer a clear next step at the end of the message.\n"
        "- Acknowledge any photos or attachments the customer has shared when relevant.\n\n"
        "Tone guide:\n"
        f"{tone_profile}\n\n"
        f"Service menu and starting prices:\n{price_list}"
    )


def _normalize_history_item(item: Dict[str, Any]) -> Dict[str, Any]:
    """Ensure every history item uses the structured Responses API format."""

    role = item.get("role", "user")
    content = item.get("content")

    if isinstance(content, str):
        return {
            "role": role,
            "content": [{"type": "text", "text": content}],
        }

    if isinstance(content, list):
        blocks: List[Dict[str, Any]] = []
        for block in content:
            if isinstance(block, dict) and block.get("type") in {"text", "input_text"}:
                text = block.get("text") or block.get("input_text")
                if isinstance(text, str) and text.strip():
                    blocks.append({"type": "text", "text": text.strip()})
            elif isinstance(block, dict) and block.get("type") == "input_image":
                image_url = block.get("image_url")
                if isinstance(image_url, dict) and image_url.get("url"):
                    blocks.append({"type": "input_image", "image_url": image_url})
        if blocks:
            return {"role": role, "content": blocks}

    return {
        "role": role,
        "content": [
            {
                "type": "text",
                "text": "Previous message unavailable due to unsupported format.",
            }
        ],
    }


def generate_reply(
    conversation_history: List[Dict[str, Any]],
    price_list_path: Path,
    tone_profile_path: Path,
    model: str = "gpt-4o-mini",
    temperature: float = 0.6,
) -> str:
    """Return a reply string generated by the OpenAI Responses API."""
    client = OpenAI()

    if not conversation_history:
        raise ValueError("Conversation history is required to draft a reply.")

    price_list = _load_price_list(price_list_path)
    tone_profile = _load_tone_profile(tone_profile_path)
    system_prompt = _build_system_prompt(price_list, tone_profile)

    chat_history: List[Dict[str, Any]] = [
        {"role": "system", "content": [{"type": "text", "text": system_prompt}]}
    ]

    chat_history.extend(_normalize_history_item(item) for item in conversation_history)

    response = client.responses.create(
        model=model,
        temperature=temperature,
        input=chat_history,
    )

    return response.output[0].content[0].text.strip()


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for testing the reply generator."""
    parser = argparse.ArgumentParser(
        description=(
            "Compose a reply to an inbound customer message using your price list "
            "and tone guide."
        )
    )
    parser.add_argument(
        "message",
        help="The inbound customer message. Use quotes to preserve newlines.",
    )
    parser.add_argument(
        "--price-list",
        type=Path,
        default=Path("price_list.json"),
        help="Path to the JSON price list file (default: price_list.json).",
    )
    parser.add_argument(
        "--tone-profile",
        type=Path,
        default=Path("tone_profile.md"),
        help="Path to the markdown tone profile (default: tone_profile.md).",
    )
    parser.add_argument(
        "--model",
        default="gpt-4o-mini",
        help="Model name to use for generation (default: gpt-4o-mini).",
    )
    parser.add_argument(
        "--temperature",
        type=float,
        default=0.6,
        help="Sampling temperature for the model (default: 0.6).",
    )
    return parser.parse_args()


def main() -> None:
    """Allow local CLI testing of the auto-responder."""
    args = parse_args()
    reply = generate_reply(
        conversation_history=[{"role": "user", "content": args.message}],
        price_list_path=args.price_list,
        tone_profile_path=args.tone_profile,
        model=args.model,
        temperature=args.temperature,
    )
    print(reply)


if __name__ == "__main__":
    main()
