"""Compose customer replies using the OpenAI API, price list, and tone guide."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

from openai import OpenAI


# ---------------------------------------------------------------------
# Load resources
# ---------------------------------------------------------------------
def _load_price_list(path: Path) -> str:
    """Load and format the JSON price list."""
    if not path.exists():
        raise FileNotFoundError(f"Price list file not found: {path}")

    with path.open("r", encoding="utf-8") as price_file:
        data: Dict[str, Any] = json.load(price_file)

    services: Iterable[Dict[str, Any]] = data.get("services", [])
    lines: List[str] = ["Available services and pricing:"]
    for service in services:
        name = service.get("name", "Unnamed service")
        description = service.get("description", "")
        price = service.get("price")
        price_text = f"£{price}" if price is not None else "price upon request"
        if description:
            lines.append(f"- {name} ({price_text}): {description}")
        else:
            lines.append(f"- {name} ({price_text})")

    if len(lines) == 1:
        lines.append("- (No services configured)")
    return "\n".join(lines)


def _load_tone_profile(path: Path) -> str:
    """Load the tone guide markdown file."""
    if not path.exists():
        raise FileNotFoundError(f"Tone profile file not found: {path}")
    return path.read_text(encoding="utf-8").strip()


# ---------------------------------------------------------------------
# Prompt building
# ---------------------------------------------------------------------
def _build_system_prompt(price_list: str, tone_profile: str) -> str:
    """Combine tone and service info into the system message."""
    return (
        "You are PowWash's virtual assistant replying to WhatsApp enquiries about "
        "exterior cleaning quotes.\n"
        "In every response you must:\n"
        "- Follow the tone guide below.\n"
        "- Reference offerings only from the provided service menu.\n"
        "- Gather any missing details that affect pricing (surface type, size, access, preferred times).\n"
        "- Offer a clear next step at the end of the message.\n"
        "- Acknowledge any photos or attachments the customer has shared when relevant.\n\n"
        "Tone guide:\n"
        f"{tone_profile}\n\n"
        f"Service menu and starting prices:\n{price_list}"
    )


# ---------------------------------------------------------------------
# Core AI logic
# ---------------------------------------------------------------------
def generate_reply(
    message: str,
    price_list_path: Path,
    tone_profile_path: Path,
    model: str = "gpt-4o-mini",
    temperature: float = 0.6,
    attachments: Optional[List[Any]] = None,
) -> str:
    """
    Return a reply string generated by the OpenAI Responses API.

    attachments may contain plain URLs, local file paths, or dicts such as:
      {"url": "https://example.com/uploads/img.jpg", "content_type": "image/jpeg"}
    """
    client = OpenAI()

    # Load resources
    price_list = _load_price_list(price_list_path)
    tone_profile = _load_tone_profile(tone_profile_path)
    system_prompt = _build_system_prompt(price_list, tone_profile)

    # Normalize attachments
    normalized_attachments: List[str] = []
    for att in attachments or []:
        if isinstance(att, str) and att.strip():
            normalized_attachments.append(att.strip())
        elif isinstance(att, dict):
            value = att.get("path") or att.get("local_path") or att.get("url")
            if isinstance(value, str) and value.strip():
                normalized_attachments.append(value.strip())

    # ---------------- Corrected structure for Responses API ----------------
    user_content: List[Dict[str, Any]] = [
        {"type": "input_text", "text": message}
    ]

    for attachment in normalized_attachments:
        # Publicly accessible image
        if attachment.lower().startswith(("http://", "https://")):
            user_content.append({
                "type": "input_image",
                "image_url": attachment,
            })
            continue

        # Local image files
        file_path = Path(attachment)
        if not file_path.is_file():
            continue
        try:
            # Serve via Flask public URL (e.g. /uploads/...)
            local_url = f"http://127.0.0.1:5002/uploads/{file_path.name}"
            user_content.append({
                "type": "input_image",
                "image_url": local_url,
            })
        except Exception:
            continue

    # Call OpenAI
    try:
        response = client.responses.create(
            model=model,
            temperature=temperature,
            input=[
                {"role": "system", "content": [{"type": "input_text", "text": system_prompt}]},
                {"role": "user", "content": user_content},
            ],
        )
        return response.output[0].content[0].text.strip()
    except Exception as e:
        print(f"⚠️ Responses API failed: {e}")
        try:
            completion = client.chat.completions.create(
                model=model,
                temperature=temperature,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": message},
                ],
            )
            return completion.choices[0].message.content.strip()
        except Exception as e2:
            print(f"❌ Chat Completions also failed: {e2}")
            return "(No AI reply generated — check model output format.)"


# ---------------------------------------------------------------------
# CLI testing
# ---------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compose a reply to an inbound customer message using your price list and tone guide."
    )
    parser.add_argument("message", help="The inbound customer message.")
    parser.add_argument("--price-list", type=Path, default=Path("price_list.json"))
    parser.add_argument("--tone-profile", type=Path, default=Path("tone_profile.md"))
    parser.add_argument("--model", default="gpt-4o-mini")
    parser.add_argument("--temperature", type=float, default=0.6)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    reply = generate_reply(
        message=args.message,
        price_list_path=args.price_list,
        tone_profile_path=args.tone_profile,
        model=args.model,
        temperature=args.temperature,
    )
    print(reply)


if __name__ == "__main__":
    main()
