// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpQ89eO4owkZRVepC1i24LaMgExLGXs_c',
    appId: '1:368120327650:web:7b9ea29b8d4f16406f5dbb',
    messagingSenderId: '368120327650',
    projectId: 'pow-ai-messaging-app',
    authDomain: 'pow-ai-messaging-app.firebaseapp.com',
    storageBucket: 'pow-ai-messaging-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIY1qvZXq0VVoare3SIuhaK5HN48O6Kdo',
    appId: '1:368120327650:android:d2ec342112b4779b6f5dbb',
    messagingSenderId: '368120327650',
    projectId: 'pow-ai-messaging-app',
    storageBucket: 'pow-ai-messaging-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGtvxGkvur8P4t8tzR6NITvMGzKY9-U6M',
    appId: '1:368120327650:ios:7fe46aba71d3d9696f5dbb',
    messagingSenderId: '368120327650',
    projectId: 'pow-ai-messaging-app',
    storageBucket: 'pow-ai-messaging-app.firebasestorage.app',
    iosBundleId: 'com.example.powwashWorkspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGtvxGkvur8P4t8tzR6NITvMGzKY9-U6M',
    appId: '1:368120327650:ios:7fe46aba71d3d9696f5dbb',
    messagingSenderId: '368120327650',
    projectId: 'pow-ai-messaging-app',
    storageBucket: 'pow-ai-messaging-app.firebasestorage.app',
    iosBundleId: 'com.example.powwashWorkspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpQ89eO4owkZRVepC1i24LaMgExLGXs_c',
    appId: '1:368120327650:web:e64092c0d17d7b8e6f5dbb',
    messagingSenderId: '368120327650',
    projectId: 'pow-ai-messaging-app',
    authDomain: 'pow-ai-messaging-app.firebaseapp.com',
    storageBucket: 'pow-ai-messaging-app.firebasestorage.app',
  );
}
